// Address Label Component
// Generated by Cradle

'use client';

import { useAddressDisplay } from '@/hooks/useAddressLabels';

interface AddressLabelProps {
  address: string;
  showFullOnHover?: boolean;
  className?: string;
}

export function AddressLabel({ address, showFullOnHover = true, className }: AddressLabelProps) {
  const { displayName, labels, isLoading } = useAddressDisplay(address);

  if (isLoading) {
    return (
      <span className={`inline-block h-4 w-24 bg-zinc-700 rounded animate-pulse ${className}`} />
    );
  }

  return (
    <span 
      className={`inline-flex items-center gap-1 text-sm ${className}`}
      title={showFullOnHover ? address : undefined}
    >
      <span className="text-zinc-300">{displayName}</span>
      {labels?.category && (
        <span className="px-1.5 py-0.5 text-xs bg-zinc-700 text-zinc-400 rounded">
          {labels.category}
        </span>
      )}
    </span>
  );
}

export default AddressLabel;