// DEX Volume Chart Component
// Generated by Cradle

'use client';

import { useDEXVolumeStats } from '@/hooks/useDEXVolume';

interface DEXVolumeChartProps {
  blockchain?: string;
  days?: number;
  protocol?: string;
  className?: string;
}

export function DEXVolumeChart({ blockchain, days, protocol, className }: DEXVolumeChartProps) {
  const { volumes, totalVolume, totalTrades, isLoading, error } = useDEXVolumeStats({ 
    blockchain, 
    days, 
    protocol 
  });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
        <div className="animate-pulse space-y-3">
          <div className="h-6 bg-zinc-700 rounded w-1/3" />
          <div className="h-32 bg-zinc-700 rounded" />
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load volume data</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <h3 className="text-sm font-medium text-zinc-400 mb-4">DEX Volume</h3>
      <div className="grid grid-cols-2 gap-4 mb-4">
        <div>
          <p className="text-xs text-zinc-500">Total Volume</p>
          <p className="text-lg font-bold text-white">
            ${(totalVolume / 1e6).toFixed(2)}M
          </p>
        </div>
        <div>
          <p className="text-xs text-zinc-500">Total Trades</p>
          <p className="text-lg font-bold text-white">
            {totalTrades.toLocaleString()}
          </p>
        </div>
      </div>
      <div className="h-32 flex items-end gap-1">
        {volumes?.map((v, i) => {
          const maxVol = Math.max(...(volumes?.map(x => x.volume_usd) ?? [1]));
          const height = (v.volume_usd / maxVol) * 100;
          return (
            <div
              key={i}
              className="flex-1 bg-cyan-500/60 rounded-t hover:bg-cyan-500 transition-colors"
              style={{ height: `${Math.max(height, 4)}%` }}
              title={`${v.date}: $${v.volume_usd.toLocaleString()}`}
            />
          );
        })}
      </div>
    </div>
  );
}

export default DEXVolumeChart;