// Gas Price Card Component
// Generated by Cradle

'use client';

import { useGasPrice } from '@/hooks/useGasPrice';

interface GasPriceCardProps {
  blockchain?: string;
  className?: string;
}

export function GasPriceCard({ blockchain, className }: GasPriceCardProps) {
  const { data: gasData, isLoading, error } = useGasPrice({ blockchain });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 animate-pulse ${className}`}>
        <div className="h-4 bg-zinc-700 rounded w-1/3 mb-2" />
        <div className="h-8 bg-zinc-700 rounded w-1/2" />
      </div>
    );
  }

  if (error || !gasData) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load gas prices</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-sm font-medium text-zinc-400">Gas Price</h3>
        <span className="text-xs text-zinc-500">{gasData.blockchain}</span>
      </div>
      <p className="text-2xl font-bold text-white">
        {gasData.current_gas_price_gwei.toFixed(2)} Gwei
      </p>
      <div className="mt-3 grid grid-cols-3 gap-2 text-xs">
        <div>
          <p className="text-zinc-500">Low</p>
          <p className="text-green-400">{gasData.min_gas_price_24h.toFixed(1)}</p>
        </div>
        <div>
          <p className="text-zinc-500">Avg</p>
          <p className="text-yellow-400">{gasData.avg_gas_price_24h.toFixed(1)}</p>
        </div>
        <div>
          <p className="text-zinc-500">High</p>
          <p className="text-red-400">{gasData.max_gas_price_24h.toFixed(1)}</p>
        </div>
      </div>
    </div>
  );
}

export default GasPriceCard;