// Protocol TVL Card Component
// Generated by Cradle

'use client';

import { useProtocolTVL } from '@/hooks/useProtocolTVL';

interface ProtocolTVLCardProps {
  protocol: string;
  blockchain?: string;
  className?: string;
}

export function ProtocolTVLCard({ protocol, blockchain, className }: ProtocolTVLCardProps) {
  const { data: tvl, isLoading, error } = useProtocolTVL({ protocol, blockchain });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 animate-pulse ${className}`}>
        <div className="h-4 bg-zinc-700 rounded w-1/3 mb-2" />
        <div className="h-8 bg-zinc-700 rounded w-1/2" />
      </div>
    );
  }

  if (error || !tvl) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load TVL</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-sm font-medium text-zinc-400">{tvl.protocol}</h3>
        <span className="text-xs text-zinc-500">{tvl.blockchain}</span>
      </div>
      <p className="text-2xl font-bold text-white">
        ${(tvl.tvl_usd / 1e6).toFixed(2)}M
      </p>
      <p className={`text-sm mt-1 ${tvl.change_24h_percent >= 0 ? 'text-green-400' : 'text-red-400'}`}>
        {tvl.change_24h_percent >= 0 ? '+' : ''}{tvl.change_24h_percent.toFixed(2)}% (24h)
      </p>
    </div>
  );
}

export default ProtocolTVLCard;