// Token Price Card Component
// Generated by Cradle

'use client';

import { useTokenPrice } from '@/hooks/useTokenPrice';

interface TokenPriceCardProps {
  blockchain: string;
  contractAddress: string;
  className?: string;
}

export function TokenPriceCard({ blockchain, contractAddress, className }: TokenPriceCardProps) {
  const { data: price, isLoading, error } = useTokenPrice({ blockchain, contractAddress });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 animate-pulse ${className}`}>
        <div className="h-4 bg-zinc-700 rounded w-1/3 mb-2" />
        <div className="h-8 bg-zinc-700 rounded w-1/2" />
      </div>
    );
  }

  if (error || !price) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load price</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm text-zinc-400">{price.symbol}</span>
        <span className="text-xs text-zinc-500">{price.blockchain}</span>
      </div>
      <p className="text-2xl font-bold text-white">
        ${price.price.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 6 })}
      </p>
    </div>
  );
}

export default TokenPriceCard;