// Address Labels Hook
// Generated by Cradle

'use client';

import { useQuery } from '@tanstack/react-query';
import { duneClient, type AddressLabel } from '@/lib/dune-client';

export function useAddressLabels(address?: string) {
  return useQuery({
    queryKey: ['dune-address-labels', address],
    queryFn: () => duneClient.getAddressLabels(address!),
    enabled: !!address,
    staleTime: 86400000, // 24 hours
  });
}

export function useAddressDisplay(address?: string) {
  const { data: labels, isLoading } = useAddressLabels(address);
  
  const displayName = labels?.ens_name 
    ?? labels?.labels?.[0] 
    ?? (address ? `${address.slice(0, 6)}...${address.slice(-4)}` : '');

  return {
    displayName,
    labels,
    isLoading,
  };
}