// Dune Query Hook
// Generated by Cradle

'use client';

import { useState, useCallback } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { duneClient, type DuneExecuteParams, type DuneQueryResult } from '@/lib/dune-client';

export interface UseDuneQueryOptions {
  enabled?: boolean;
  refetchInterval?: number;
}

export function useDuneQuery<T = Record<string, unknown>>(
  params?: DuneExecuteParams,
  options?: UseDuneQueryOptions
) {
  return useQuery({
    queryKey: ['dune-query', params?.sql],
    queryFn: () => duneClient.executeAndWait<T>(params!),
    enabled: !!params?.sql && (options?.enabled ?? true),
    refetchInterval: options?.refetchInterval,
  });
}

export function useDuneMutation<T = Record<string, unknown>>() {
  return useMutation({
    mutationFn: (params: DuneExecuteParams) => duneClient.executeAndWait<T>(params),
  });
}

export function useDuneLazyQuery<T = Record<string, unknown>>() {
  const [data, setData] = useState<DuneQueryResult<T> | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const execute = useCallback(async (params: DuneExecuteParams) => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await duneClient.executeAndWait<T>(params);
      setData(result);
      return result;
    } catch (err) {
      setError(err as Error);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, []);

  return { data, isLoading, error, execute };
}