// DEX Volume Hook
// Generated by Cradle

'use client';

import { useQuery } from '@tanstack/react-query';
import { duneClient, type DEXVolume } from '@/lib/dune-client';

export interface UseDEXVolumeParams {
  blockchain?: string;
  days?: number;
  protocol?: string;
  enabled?: boolean;
}

export function useDEXVolume(params?: UseDEXVolumeParams) {
  return useQuery({
    queryKey: ['dune-dex-volume', params?.blockchain, params?.days, params?.protocol],
    queryFn: () => duneClient.getDEXVolume(
      params?.blockchain ?? 'arbitrum',
      params?.days ?? 7,
      params?.protocol
    ),
    enabled: params?.enabled ?? true,
    staleTime: 300000,
  });
}

export function useDEXVolumeStats(params?: UseDEXVolumeParams) {
  const { data: volumes, ...rest } = useDEXVolume(params);
  
  const totalVolume = volumes?.reduce((sum, v) => sum + v.volume_usd, 0) ?? 0;
  const totalTrades = volumes?.reduce((sum, v) => sum + v.trade_count, 0) ?? 0;
  const avgDailyVolume = volumes?.length ? totalVolume / volumes.length : 0;

  return {
    ...rest,
    volumes,
    totalVolume,
    totalTrades,
    avgDailyVolume,
  };
}