// Gas Price Hook
// Generated by Cradle

'use client';

import { useQuery } from '@tanstack/react-query';
import { duneClient, type GasPriceData } from '@/lib/dune-client';

export interface UseGasPriceParams {
  blockchain?: string;
  enabled?: boolean;
  refetchInterval?: number;
}

export function useGasPrice(params?: UseGasPriceParams) {
  return useQuery({
    queryKey: ['dune-gas-price', params?.blockchain],
    queryFn: () => duneClient.getGasPrice(params?.blockchain ?? 'arbitrum'),
    enabled: params?.enabled ?? true,
    refetchInterval: params?.refetchInterval ?? 60000,
    staleTime: 30000,
  });
}