// Protocol TVL Hook
// Generated by Cradle

'use client';

import { useQuery } from '@tanstack/react-query';
import { duneClient, type ProtocolTVL } from '@/lib/dune-client';

export interface UseProtocolTVLParams {
  protocol: string;
  blockchain?: string;
  enabled?: boolean;
}

export function useProtocolTVL(params: UseProtocolTVLParams) {
  return useQuery({
    queryKey: ['dune-protocol-tvl', params.protocol, params.blockchain],
    queryFn: () => duneClient.getProtocolTVL(
      params.protocol,
      params.blockchain ?? 'arbitrum'
    ),
    enabled: !!params.protocol && (params.enabled ?? true),
    staleTime: 600000,
  });
}