// Token Price Hook
// Generated by Cradle

'use client';

import { useQuery } from '@tanstack/react-query';
import { duneClient, type TokenPrice } from '@/lib/dune-client';

export interface UseTokenPriceParams {
  blockchain: string;
  contractAddress: string;
  enabled?: boolean;
  refetchInterval?: number;
}

export function useTokenPrice(params: UseTokenPriceParams) {
  return useQuery({
    queryKey: ['dune-token-price', params.blockchain, params.contractAddress],
    queryFn: () => duneClient.getTokenPrice(params.blockchain, params.contractAddress),
    enabled: params.enabled ?? true,
    refetchInterval: params.refetchInterval ?? 60000,
    staleTime: 30000,
  });
}

export function useMultipleTokenPrices(
  tokens: Array<{ blockchain: string; contractAddress: string }>,
  options?: { enabled?: boolean; refetchInterval?: number }
) {
  return useQuery({
    queryKey: ['dune-token-prices', tokens],
    queryFn: async () => {
      const results = await Promise.all(
        tokens.map(t => duneClient.getTokenPrice(t.blockchain, t.contractAddress))
      );
      return results.filter((r): r is TokenPrice => r !== null);
    },
    enabled: options?.enabled ?? true,
    refetchInterval: options?.refetchInterval ?? 60000,
  });
}